name: Production Like Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Test application
        run: |
          test -f app.sh
          grep "Homelab application started" app.sh
          echo "Tests passed"


  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/homelab-app:${{ github.sha }}


  smoke-test:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/homelab-app:${{ github.sha }}

      - name: Run container
        run: |
          docker run --rm \
            ghcr.io/${{ github.repository_owner }}/homelab-app:${{ github.sha }} \
            | tee container.log

      - name: Smoke test
        run: |
          grep "Homelab application started" container.log
          echo "Smoke test passed"


  deploy:
    needs: smoke-test
    runs-on: ubuntu-latest

    steps:
      - name: Simulate deployment
        run: |
          echo "Deploying image:"
          echo "ghcr.io/${{ github.repository_owner }}/homelab-app:${{ github.sha }}"
          echo "Deployment completed"
